name: "publish packages"

# The workflow to execute on is comments that are newly created
on:
  push:
    branches: 
      - master
  workflow_dispatch:

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout your projects repository based on the ref provided by the branch-deploy step
      - uses: actions/checkout@v4
      - name: move files
        run: rm $(ls | sed -e 's/packages//') -r |
             mv packages/* ./ |
             rm -r packages
      - uses: EndBug/add-and-commit@v9
        with:
          new_branch: package
